name: Poly
version: ${project.version}
main: eu.okaeri.poly.bukkit.ext.PolyKotlinScriptExtension
description: Kotlin Script extension for Poly
website: https://github.com/OkaeriPoland/okaeri-poly
author: 'Bartosz Stefańczyk <bartosz@cdfn.dev>'
api-version: 1.13
depend:
  - Poly
